### ISSUE TITLE
Todo semana

### ISSUE THREAD

**Issue by RochaCarla** [unb-mds/2023-2-Squad04#3]
- [x] Scrum
- [x] Configurar ambiente - instalar SO + git + vscode + pyton3.x
- [x] estudar os projetos (querido diario + pacote mais_
- [ ] Tarefa: abrir uma issue com 3 opções em ordem de prioridade d projeto que vcs quem

**Comment by DaniloCTM** [comment]
Issue de exemplo criada pela professora.
