### ISSUE TITLE
 Criar o Roadmap do Projeto Licitaíba

### ISSUE THREAD

**Issue by Carlos-kadu** [unb-mds/2023-2-Squad04#38]
# Criar o Roadmap do Projeto Licitaíba

## Descrição
Esta issue tem como objetivo criar um roadmap detalhado para o projeto. O roadmap servirá como uma representação visual das metas, marcos e entregas planejados para o projeto ao longo do tempo.

## Tarefas
- [x] Identificação de Metas e Marcos
- [x] Estabelecimento de Prazos
- [x] Priorização de Tarefas
- [x] Criação do Roadmap

## Critérios de Aceitação

- [x] Um roadmap detalhado e visual foi criado e está disponível para a equipe e as partes interessadas.
- [x] As datas e prazos são claros e refletem as prioridades do projeto.

**Comment by Carlos-kadu** [comment]
Roadmap disponível na documentação do projeto em: https://unb-mds.github.io/2023-2-Squad04/#/arquivos/index

**Comment by Carlos-kadu** [comment]
Issue concluída
